## Local platform constraints for exp3-04_dot_matrix_led
## Device: xc7a100tfgg484-3
## Dot matrix uses BSW-A group for row/column multiplexing
## Updated: 2026-05-26

## Independent core-board 125 MHz differential system clock, matching the
## verified exp2-01 counter design. R4/T4 = SYS_CLK_P/N, Bank 34 MRCC pair.
set_property -quiet PACKAGE_PIN R4 [get_ports -quiet clk_in_p]
set_property -quiet PACKAGE_PIN T4 [get_ports -quiet clk_in_n]
set_property -quiet IOSTANDARD DIFF_SSTL15 [get_ports -quiet {clk_in_p clk_in_n}]
create_clock -name sys_clk -period 8.000 [get_ports -quiet clk_in_p]

set_property -quiet PACKAGE_PIN AB6  [get_ports -quiet {PI[0]}]
set_property -quiet PACKAGE_PIN V9  [get_ports -quiet {PI[1]}]
set_property -quiet PACKAGE_PIN V8  [get_ports -quiet {PI[2]}]
set_property -quiet PACKAGE_PIN AA8  [get_ports -quiet {PI[3]}]
set_property -quiet PACKAGE_PIN AB8  [get_ports -quiet {PI[4]}]
set_property -quiet PACKAGE_PIN Y8  [get_ports -quiet {PI[5]}]
set_property -quiet PACKAGE_PIN Y7  [get_ports -quiet {PI[6]}]
set_property -quiet PACKAGE_PIN W9  [get_ports -quiet {PI[7]}]
set_property -quiet PACKAGE_PIN Y12  [get_ports -quiet {PI[8]}]
set_property -quiet PACKAGE_PIN AA13  [get_ports -quiet {PI[9]}]
set_property -quiet PACKAGE_PIN AB13  [get_ports -quiet {PI[10]}]
set_property -quiet PACKAGE_PIN T16  [get_ports -quiet {PI[11]}]
set_property -quiet PACKAGE_PIN U16  [get_ports -quiet {PI[12]}]
set_property -quiet PACKAGE_PIN D15  [get_ports -quiet {PI[13]}]
set_property -quiet PACKAGE_PIN B22  [get_ports -quiet {PI[14]}]
set_property -quiet PACKAGE_PIN T6  [get_ports -quiet {PI[15]}]
set_property -quiet IOSTANDARD LVCMOS33 [get_ports -quiet {PI[0] PI[1] PI[2] PI[3] PI[4] PI[5] PI[6] PI[7] PI[8] PI[9] PI[10] PI[11] PI[12] PI[13] PI[14] PI[15]}]

set_property -quiet PACKAGE_PIN J19  [get_ports -quiet {PO[0]}]
set_property -quiet PACKAGE_PIN F20  [get_ports -quiet {PO[1]}]
set_property -quiet PACKAGE_PIN G18  [get_ports -quiet {PO[2]}]
set_property -quiet PACKAGE_PIN J20  [get_ports -quiet {PO[3]}]
set_property -quiet PACKAGE_PIN G17  [get_ports -quiet {PO[4]}]
set_property -quiet PACKAGE_PIN J21  [get_ports -quiet {PO[5]}]
set_property -quiet PACKAGE_PIN F19  [get_ports -quiet {PO[6]}]
set_property -quiet PACKAGE_PIN H19  [get_ports -quiet {PO[7]}]
set_property -quiet PACKAGE_PIN F21  [get_ports -quiet {PO[8]}]
set_property -quiet PACKAGE_PIN A19  [get_ports -quiet {PO[9]}]
set_property -quiet PACKAGE_PIN A18  [get_ports -quiet {PO[10]}]
set_property -quiet PACKAGE_PIN C19  [get_ports -quiet {PO[11]}]
set_property -quiet PACKAGE_PIN B20  [get_ports -quiet {PO[12]}]
set_property -quiet PACKAGE_PIN A21  [get_ports -quiet {PO[13]}]
set_property -quiet PACKAGE_PIN B21  [get_ports -quiet {PO[14]}]
set_property -quiet PACKAGE_PIN A20  [get_ports -quiet {PO[15]}]
set_property -quiet PACKAGE_PIN T3  [get_ports -quiet {PO[16]}]
set_property -quiet PACKAGE_PIN U6  [get_ports -quiet {PO[17]}]
set_property -quiet PACKAGE_PIN AB16  [get_ports -quiet {PO[18]}]
set_property -quiet PACKAGE_PIN V5  [get_ports -quiet {PO[19]}]
set_property -quiet PACKAGE_PIN R6  [get_ports -quiet {PO[20]}]
set_property -quiet PACKAGE_PIN Y13  [get_ports -quiet {PO[21]}]
set_property -quiet PACKAGE_PIN L19  [get_ports -quiet {PO[22]}]
set_property -quiet PACKAGE_PIN L20  [get_ports -quiet {PO[23]}]
set_property -quiet PACKAGE_PIN C22  [get_ports -quiet {PO[24]}]
set_property -quiet PACKAGE_PIN W11  [get_ports -quiet {PO[25]}]
set_property -quiet PACKAGE_PIN W12  [get_ports -quiet {PO[26]}]
set_property -quiet PACKAGE_PIN C14  [get_ports -quiet {PO[27]}]
set_property -quiet PACKAGE_PIN Y9  [get_ports -quiet {PO[28]}]
set_property -quiet PACKAGE_PIN L6  [get_ports -quiet {PO[29]}]
set_property -quiet PACKAGE_PIN G4  [get_ports -quiet {PO[30]}]
set_property -quiet PACKAGE_PIN Y11  [get_ports -quiet {PO[31]}]
set_property -quiet IOSTANDARD LVCMOS33 [get_ports -quiet {PO[0] PO[1] PO[2] PO[3] PO[4] PO[5] PO[6] PO[7] PO[8] PO[9] PO[10] PO[11] PO[12] PO[13] PO[14] PO[15] PO[16] PO[17] PO[18] PO[19] PO[20] PO[21] PO[22] PO[23] PO[24] PO[25] PO[26] PO[27] PO[28] PO[29] PO[30] PO[31]}]

set_property -quiet PACKAGE_PIN J16  [get_ports -quiet {PIO[0]}]
set_property -quiet PACKAGE_PIN E22  [get_ports -quiet {PIO[1]}]
set_property -quiet PACKAGE_PIN F18  [get_ports -quiet {PIO[2]}]
set_property -quiet PACKAGE_PIN E19  [get_ports -quiet {PIO[3]}]
set_property -quiet PACKAGE_PIN D21  [get_ports -quiet {PIO[4]}]
set_property -quiet PACKAGE_PIN D17  [get_ports -quiet {PIO[5]}]
set_property -quiet PACKAGE_PIN D19  [get_ports -quiet {PIO[6]}]
set_property -quiet PACKAGE_PIN C17  [get_ports -quiet {PIO[7]}]
set_property -quiet PACKAGE_PIN W5  [get_ports -quiet {PIO[8]}]
set_property -quiet PACKAGE_PIN E13  [get_ports -quiet {PIO[9]}]
set_property -quiet PACKAGE_PIN D14  [get_ports -quiet {PIO[10]}]
set_property -quiet PACKAGE_PIN B13  [get_ports -quiet {PIO[11]}]
set_property -quiet PACKAGE_PIN C13  [get_ports -quiet {PIO[12]}]
set_property -quiet PACKAGE_PIN E18  [get_ports -quiet {PIO[13]}]
set_property -quiet PACKAGE_PIN L14  [get_ports -quiet {PIO[14]}]
set_property -quiet PACKAGE_PIN L15  [get_ports -quiet {PIO[15]}]
set_property -quiet IOSTANDARD LVCMOS33 [get_ports -quiet {PIO[0] PIO[1] PIO[2] PIO[3] PIO[4] PIO[5] PIO[6] PIO[7] PIO[8] PIO[9] PIO[10] PIO[11] PIO[12] PIO[13] PIO[14] PIO[15]}]

## Dot matrix I_COL (4 column selects) — BANK14
set_property -quiet PACKAGE_PIN P14  [get_ports -quiet {I_COL[0]}]
set_property -quiet PACKAGE_PIN R14  [get_ports -quiet {I_COL[1]}]
set_property -quiet PACKAGE_PIN P19  [get_ports -quiet {I_COL[2]}]
set_property -quiet PACKAGE_PIN R19  [get_ports -quiet {I_COL[3]}]
set_property -quiet IOSTANDARD LVCMOS33 [get_ports -quiet {I_COL[0] I_COL[1] I_COL[2] I_COL[3]}]

## Dot matrix I_ROW (16 row lines) — BANK14
set_property -quiet PACKAGE_PIN T21  [get_ports -quiet {I_ROW[0]}]
set_property -quiet PACKAGE_PIN U21  [get_ports -quiet {I_ROW[1]}]
set_property -quiet PACKAGE_PIN U20  [get_ports -quiet {I_ROW[2]}]
set_property -quiet PACKAGE_PIN V20  [get_ports -quiet {I_ROW[3]}]
set_property -quiet PACKAGE_PIN W20  [get_ports -quiet {I_ROW[4]}]
set_property -quiet PACKAGE_PIN T20  [get_ports -quiet {I_ROW[5]}]
set_property -quiet PACKAGE_PIN AB21 [get_ports -quiet {I_ROW[6]}]
set_property -quiet PACKAGE_PIN AB22 [get_ports -quiet {I_ROW[7]}]
set_property -quiet PACKAGE_PIN N13  [get_ports -quiet {I_ROW[8]}]
set_property -quiet PACKAGE_PIN V22  [get_ports -quiet {I_ROW[9]}]
set_property -quiet PACKAGE_PIN W21  [get_ports -quiet {I_ROW[10]}]
set_property -quiet PACKAGE_PIN W22  [get_ports -quiet {I_ROW[11]}]
set_property -quiet PACKAGE_PIN R18  [get_ports -quiet {I_ROW[12]}]
set_property -quiet PACKAGE_PIN Y19  [get_ports -quiet {I_ROW[13]}]
set_property -quiet PACKAGE_PIN V18  [get_ports -quiet {I_ROW[14]}]
set_property -quiet PACKAGE_PIN V19  [get_ports -quiet {I_ROW[15]}]
set_property -quiet IOSTANDARD LVCMOS33 [get_ports -quiet {I_ROW[0] I_ROW[1] I_ROW[2] I_ROW[3] I_ROW[4] I_ROW[5] I_ROW[6] I_ROW[7] I_ROW[8] I_ROW[9] I_ROW[10] I_ROW[11] I_ROW[12] I_ROW[13] I_ROW[14] I_ROW[15]}]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLDOWN [current_design]
